### ISSUE TITLE
修改个人登录密码

### ISSUE THREAD

**Issue by dianhsu** [4ddl/ddlf#15]
RT

- 修改个人登录密码之后，后端会清除个人的登录状态，前端需要刷新状态信息

**Comment by dianhsu** [comment]
补充后台接口相关参数
请求URL：`/api/user/password`
请求方式：`PUT`
请求参数：
| 参数 | 类型 | 介绍 |
| --- | --- | --- |
| `old_password` | string | 原始密码 |
| `new_password` | string | 新密码 |
 参考数据：
```json
{
    "old_password": "123456",
    "new_password": "123123123"
}

```

@JuYanYan

**Comment by JuYanYan** [comment]
该接口是否已经合并到后端? 显示404 @dianhsu

**Comment by dianhsu** [comment]
已经合并到后端了

**Comment by dianhsu** [comment]
我描述的有点问题，所有的URL结束的时候，都需要有个反斜杠才有效
